USE VARGS;

ALTER TABLE desaparecidos
  MODIFY COLUMN status ENUM('PENDENTE','ATIVO','ENCONTRADO','REJEITADO','ARQUIVADO','EXCLUIDO') NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE historico_desaparecido
  MODIFY COLUMN acao ENUM('CADASTRO','APROVACAO','REJEICAO','SOLICITACAO_REENCONTRO','REENCONTRO_APROVADO','REENCONTRO_REJEITADO','ARQUIVAMENTO','EXCLUSAO') NOT NULL;
